### ISSUE TITLE
missing module on install "Text.PrettyPrint.Prettyprinter"

### ISSUE THREAD

**Issue by joelberkeley** [stefan-hoeck/idris2-hedgehog#1]
I installed hedgehog v0.1.0 with idris2 v0.4.0, but I'm getting
```
Uncaught error: Error: Module Text.PrettyPrint.Prettyprinter not found
```
I see this is used in the pretty-show package, which I have installed at v0.3.0. I can't see the module in that repo, or its deps.

I'm running my tests with
```
idris2 -p experimental -p elab-util -p sop -p pretty-show -p hedgehog test/XLA.idr
```
so far (I haven't figured out exactly how to do that).

**Comment by stefan-hoeck** [comment]
`Text.PrettyPrint.Prettyprinter` is part of `contrib`, which should have been installed when you installed Idris2. If you are using hedgehog in one of your own projects, you'll need to include `contrib` in the project's dependencies.
