### ISSUE TITLE
Exit status codes

### ISSUE THREAD

**Issue by bobbbay** [stefan-hoeck/idris2-hedgehog#2]
Unix has exit status codes: numbers that allow us to convey the status of a program that just ran. Among other exit codes, `0` means success, and `1` is a catch-all for all errors.

Expected: a failed test has a status code of `1`. (The status code of the previous program run can be checked with `echo $?`)
Actual: a failed test still has a status code of `0`. 

It would be great if it was possible to convey context-aware status codes in `idris2-hedgehog`.

**Comment by stefan-hoeck** [comment]
This makes a lot of sense. I'll have a look but this might take some time. Feel free to give it a try yourself. The only prerequisite: If possible, the solution should also work on the Node backend.

**Comment by joelberkeley** [comment]
@bobbbay did you come up with a workaround for now? I could grep the output for "failed" but that seems a bit fragile

**Comment by joelberkeley** [comment]
ah i've just seen `test` which says it does this
```
||| Simple test runner.
|||
||| Use this in a `main` function in order to test a list of
||| property groups. The runner will take into account several
||| command line arguments in order to adjust the number of
||| tests to be run for each property, the maximal number of
||| shrinks and the confidence value to use.
|||
||| ```idris example
||| main : IO ()
||| main = test myGroups
||| ```
|||
||| The resulting executable can then be run as follows:
|||
||| ```sh
||| build/exec/runTests -n 1000
||| ```
|||
||| It will fail with an exit code of 1 if at least one property
||| fails.
export
test : HasIO io => List Group -> io ()
```

**Comment by stefan-hoeck** [comment]
Lol. It actually does, I just checked it. Doh, didn't even know that I included this. Can this be closed then?

**Comment by bobbbay** [comment]
Yes, for sure, thanks :)
